/**
 * shared/types.ts — Extension-wide TypeScript types
 *
 * Shared between content scripts, background service worker, and panel.
 */

/** Product data scraped from an e-commerce page. */
export interface ScrapedProduct {
  url: string;
  product_id: string;
  productId: string;
  name: string | null;
  price: number | null;
  currency: string;
  rating: number | null;
  review_count: number | null;
  reviewCount: number | null;
  seller: string | null;
  category: string | null;
  image_url: string | null;
  imageUrl: string | null;
  specs: Record<string, string>;
  reviews: ScrapedReview[];
  scrapedAt: string; // ISO 8601 timestamp
  source: "trendyol" | "generic" | "demo";
}

export interface ScrapedReview {
  author?: string | null;
  rating: number | null;
  text: string;
  date: string | null;
  verified_buyer: boolean;
}

/** Backend analysis mode. */
export type AnalysisMode = "soft" | "balanced" | "strict";

/** Analysis pipeline status shown in the panel. */
export type AnalysisStatus =
  | "idle"
  | "analyzing"
  | "questions"
  | "complete"
  | "error";

/** A question generated by the Need Analyzer agent. */
export interface NeedQuestion {
  id: string;
  text: string;
  type: "multiple_choice" | "yes_no" | "scale";
  options: string[] | null;
  triggered_by: string | null;
}

/** A single SSE event forwarded from the background service worker. */
export interface SSEEvent {
  eventType: string;
  data: unknown;
}

/** Final verdict data from the backend. */
export interface VerdictData {
  verdict: string;
  score: number;
  score_breakdown: Record<string, number>;
  headline: string;
  body: string;
  suggested_action?: string;
}

/** Summary of a completed analysis decision. */
export interface DecisionResult {
  decisionId: string;
  verdict: string;
  score: number;
  headline: string;
  body: string;
  suggestedAction?: string;
}
